Implement book editing
GeyserMC/Geyser pull request #1117
Opened 2020-08-10 20:04 UTC by DoctorMacc

Updates the PR created by @ForceUpdate1 for 1.16 support. Seems to work fine now that hand support is in MCProtocolLib.

2020-08-12 15:15 UTC, DoctorMacc commented
!start-test-server

2020-08-12 15:33 UTC, toinouH commented
It doesn't fixe the problem for the moment

2020-08-12 19:07 UTC, DoctorMacc commented
!start-test-server

2020-08-12 19:08 UTC, DoctorMacc commented
!stop-test-server

2020-08-12 19:08 UTC, DoctorMacc commented
!start-test-server

2020-08-17 19:02 UTC, DoctorMacc commented
!start-test-server

2020-08-17 19:10 UTC, DoctorMacc commented
!stop-test-server

2020-08-17 19:11 UTC, DoctorMacc commented
!start-test-server

2020-08-17 19:21 UTC, DoctorMacc commented
!stop-test-server

2020-08-17 19:21 UTC, DoctorMacc commented
!start-test-server

2020-08-17 19:43 UTC, DoctorMacc commented
!stop-test-server

2020-08-17 19:50 UTC, DoctorMacc commented
!start-test-server

2020-09-19 00:51 UTC, DoctorMacc commented
This PR is going to be on hiatus for a while.

The problem is that Bedrock sends a book edit update multiple times, while Java just wants it after the book is finished editing. This is fine on vanilla, but server software such as Paper checks for quick book editing and kicks the user. Unlike signs, there is no final packet sent. And we can't just send the last book edit packet because there are different kinds of packets being sent.

2020-11-03 02:25 UTC, DoctorMacc commented
Thanks to @davchoo, this PR is no longer on hiatus.

2020-11-04 14:55 UTC, DoctorMacc commented
!start-test-server

2020-12-20 02:47 UTC, Hellohi3654 commented
How well does this work?

2020-12-20 02:47 UTC, Hellohi3654 commented
any major bugs?

2020-12-20 11:13 UTC, toinouH commented
@Hellohi3654 We had some issues in the past with it so.

2020-12-20 15:39 UTC, Camotoy commented
I intend on merging into master soon.

2020-12-21 00:15 UTC, Hellohi3654 commented
so should be fine to merge into my fork

2021-01-07 20:00 UTC, rtm516 requested changes

2021-01-07 20:00 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/network/session/cache/BookEditCache.java
> + * Copyright (c) 2019-2020 GeyserMC. http://geysermc.org
Needs updating to 2021
```suggestion
 * Copyright (c) 2019-2021 GeyserMC. http://geysermc.org
```

2021-01-07 20:00 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockBookEditTranslator.java
> + * Copyright (c) 2019-2020 GeyserMC. http://geysermc.org
Same as above
```suggestion
 * Copyright (c) 2019-2021 GeyserMC. http://geysermc.org
```

2021-01-07 20:16 UTC, rtm516 approved these changes

2021-01-08 00:40 UTC, merged