Added spigot only updater.
GeyserMC/Geyser pull request #1335
Opened 2020-09-24 13:53 UTC by Arcratist

2020-09-24 15:11 UTC, DoctorMacc commented
Seems fine to me, but it would be nice if we could roll out auto-updating to all platforms if possible.

2020-09-24 16:37 UTC, Arcratist commented
Spigot has an update folder that replaces the plugin jar with its contents at startup. Other platforms will be much more complicated. Ill take a look at potential solutions tomorrow some time.

2020-09-24 16:44 UTC, rtm516 requested changes
Comments should also have a space after the `//`
EG: `// Currently only Spigot works`

2020-09-24 16:44 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/command/defaults/UpdateCommand.java
> +        if (!platform.equals("Spigot")) {
This should use the enums for `PlatformType` instead

2020-09-24 16:44 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/command/defaults/UpdateCommand.java
> +                            String downloadUrl = "https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/" + URLEncoder.encode(gitProp.getProperty("git.branch"), StandardCharsets.UTF_8.toString()) + "/la
Same as above

2020-09-24 16:44 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/command/defaults/UpdateCommand.java
> +                            File downloadedFile = new File(updateFolder, platform.equals("Standalone") ? "Geyser.jar" : "Geyser-" + platform + ".jar");
Same as above

2020-09-25 09:48 UTC, Arcratist commented
Made a few changes

2020-09-25 09:50 UTC, rtm516 approved these changes

2020-09-25 19:35 UTC, lukeeey requested changes
Please use this URL as it contains the hashes as well
```
https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/api/xml?depth=2&tree=fingerprint[fileName,hash]{0,},artifacts[fileName,relativePath]
```
Also, if possible, feel free to use an XML parser (even the built-in one) to parse the above

2021-01-12 22:10 UTC, YHDiamond commented
I think this should be updated to the new CI URL.

2021-01-31 15:35 UTC, YHDiamond commented
There is a plugin that @AlysaaKobe made that does this too just saying. github.com/YHDiamond/GeyserUpdater

2021-04-22 02:36 UTC, Camotoy commented
We're going to close this PR, at least for the time being. Some form of updater is not off the table, but it will be for all platforms, not just Spigot. For now, there are community methods of autoupdating that can be used.

Thank you for the PR anyway!

2021-04-22 02:36 UTC, closed without merging