Inventory fixes
GeyserMC/Geyser pull request #1360
Opened 2020-10-04 03:11 UTC by DoctorMacc

- Grindstone is now fixed
- Smithing table now 'works' - we can guess when the client wants an output (it sends a inventory mismatch packet) and at least give the player the netherite tool.

2020-10-04 03:51 UTC, Comstepr commented
@DoctorMacc Perhaps you want to edit README.md to say that smithing table 'works'?

2020-10-04 04:10 UTC, RednedEpic requested changes

2020-10-04 04:10 UTC, RednedEpic commented on connector/src/main/java/org/geysermc/connector/network/translators/inventory/GrindstoneInventoryTranslator.java
> +            System.out.println(action.getSource().getContainerId());
This debug line should be removed.

2020-10-04 09:35 UTC, Comstepr commented
@DoctorMacc My friend said it does not work on Windows 10, can you test that out?

2020-10-04 14:07 UTC, DoctorMacc commented
What is "it"? Do grindstones not work? Does the smithing table fail to fix itself?

2020-10-05 19:54 UTC, DoctorMacc commented
@Comstepr I tested on my Android Linux wrapper and Tuinity and had no issues.

2020-10-06 04:48 UTC, zimzaza4 commented
> @Comstepr我在Android Linux包装器和Tuinity上进行了测试，没有任何问题。

Grindstone still seems to have problems

2020-10-08 07:26 UTC, paladinodeimari commented
Selected JAR = spigot_1.16.3
Server thread/INFO Enabling Geyser-Spigot v1.1.0 (build #414)

Grindstone and Smithing Table don't give back items.
[Look the video](https://drive.google.com/file/d/1r5a4qRrzyjsNvC1IFBbt4IANSLr6vooW/view?usp=sharing).

2020-10-08 09:09 UTC, Hellohi3654 commented
Try shift clicking the item out

2020-10-08 14:38 UTC, DoctorMacc commented
@zimzaza4 @paladinodeimari you need to be using the jar file located in this PR in order for the fix to go into effect!

2020-10-09 00:01 UTC, Limumcpe commented
Grindstones still not working on this PR, Spigot 1.16.3. :(
![Uploading 20201009_085825.gif…]()

2020-10-09 11:37 UTC, paladinodeimari commented
@DoctorMacc do you mean that I don't have to download [from Jenkins](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/) but from Git??!!

2020-10-09 15:01 UTC, DoctorMacc commented
Yes; there are downloads attached to this PR.

2020-10-10 10:53 UTC, Hellohi3654 commented
download this PR here 
https://github.com/GeyserMC/Geyser/pull/1360/checks

2020-10-10 17:15 UTC, paladinodeimari commented
@DoctorMacc Thank you.
I'm a little bit confused. Why have I to download it from PR? Will it never be merged with the master in Jenkins?

2020-10-10 17:16 UTC, DoctorMacc commented
It will be merged; it needs to be tested first to make sure it actually works!

2020-10-30 11:47 UTC, Cy4Shot commented
This PR, fixes firework crafting too

2020-10-30 14:36 UTC, DoctorMacc commented
Firework crafting is already fixed in master.

2020-10-30 16:28 UTC, Cy4Shot commented
> Firework crafting is already fixed in master.

its not for me, this fixed it

2020-10-30 16:34 UTC, DoctorMacc commented
Then once this is merged that will reset. Did you test on the latest Geyser? How did you try to craft the firework?

2020-10-30 16:35 UTC, Cy4Shot commented
> Then once this is merged that will reset. Did you test on the latest Geyser? How did you try to craft the firework?

standard firework crafting recipe, latest Geyser, 1.16.3 spigot

2020-11-02 21:27 UTC, rtm516 approved these changes

2020-11-09 03:17 UTC, LimuLhw commented
![Recording_2020-11-09-12-07-22(1)](https://user-images.githubusercontent.com/6559842/98496637-71318e80-2285-11eb-92dd-98f8a08f7388.gif)
grindstones are still not working on windows 10 Edition.
(Touch screen mode, and Keyboard&Mouse Mode.)

2020-12-13 10:16 UTC, zimzaza4 commented
Has this PR stopped updating?

2020-12-14 08:28 UTC, vijaypondini commented
If possible, merge this with master please. Waiting for this! :)

2020-12-26 20:39 UTC, Camotoy commented
Closing, as the inventory rewrite will fix this better.

2020-12-26 20:39 UTC, closed without merging