Add more interactive tags (mobile buttons)
GeyserMC/Geyser pull request #1443
Opened 2020-10-24 02:11 UTC by DoctorMacc

This expands our support for showing the interactive tags on touchscreen and console setups. This is not complete - specifically, the food compatibility of creatures needs to be expanded upon (I will work on this later and does not stop this PR from being mergable). This also includes:

- Creepers who are ignited with flint and steel now show up properly
- Zombie villagers now shake properly when converting and show their region outfits

2020-10-24 10:20 UTC, RehanPlayz approved these changes

2020-10-29 21:39 UTC, rtm516 requested changes

2020-10-29 21:39 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockInteractTranslator.java
> +            "cooked_rabbit");
Can these be pulled out and into the mappings files?

2020-11-12 00:11 UTC, rtm516 requested changes

2020-11-12 00:11 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/entity/living/animal/horse/AbstractHorseEntity.java
> +            metadata.getFlags().setFlag(EntityFlag.EATING, (xd & 0x10) == 0x10); //TODO: this doesn't work on a horse
This can be reverted since it's fixed in master.

2020-11-12 00:11 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/entity/living/monster/BasePiglinEntity.java
>  }
Add a newline at the end of the file

2020-11-12 00:19 UTC, rtm516 approved these changes

2020-11-12 00:28 UTC, merged