Ender dragon Melee Attacks
GeyserMC/Geyser pull request #1466
Opened 2020-10-28 15:33 UTC by davchoo

Fixes #1090

2020-10-28 15:47 UTC, DoctorMacc requested changes
Thank you so, so much.

I have yet to actually try out the code, but I think that more commenting on what variables do and how the bounding box system works would be very helpful.
I believe I also have some other miscellaneous ender dragon changes I made whilst trying to get this to work for myself; I'll PR to your PR if they're still any good.

2020-10-29 00:31 UTC, DoctorMacc commented
I tested this PR and it looked good to me. Didn't lag my Xbox One at all, which I was a little worried about because of the additional entities, but whatever the performance cost, it's worth it to add melee ender dragon support.
Davchoo, I made a PR that fixes up the entity metadata a bit, including properly updating sitting status.

2020-10-29 00:57 UTC, DoctorMacc commented
Two more things on my end, then it's good to go in my opinion:

- Can you add Javadoc comments on the segment functions? What they're trying to do is lost on me.
- Would it be more efficient to call the update bounding boxes function when `moveRelative` and `moveAbsolute` are run? For example, when the ender dragon is sitting, it isn't moving much and we don't need to process it moving. However I could absolutely be missing something so that's up for discussion.

2020-10-29 01:28 UTC, davchoo commented
The segment functions are used to store the y position and yaw of the dragon, to curl the tail when it turns. I'm not sure if the call to update the bounding boxes can be moved, since the tail straightens out after it stops moving.

2020-10-29 01:29 UTC, DoctorMacc commented
Ah, gotcha.

2020-10-29 01:29 UTC, DoctorMacc approved these changes
Looks good to me, but I will be getting a second pair of eyes on this code before merge as it's doing a lot.

2020-10-29 03:09 UTC, lukeeey commented
I would suggest testing it on a mid range Android smartphone as well

2020-10-29 20:33 UTC, rtm516 requested changes

2020-10-29 20:33 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/entity/living/monster/EnderDragonEntity.java
> +        leftWing.setPosition(rightWing.getPosition().mul(-1, 1, -1)); // Mirror horizontally
Can this be changed to extract the vector into a variable? (as below)

```java
Vector3f wingPos = Vector3f.createDirectionDeg(0, 90f - rotation.getZ()).mul(4.5f).up(2f);

rightWing.setPosition(wingPos);
leftWing.setPosition(wingPos.mul(-1, 1, -1)); // Mirror horizontally
```

2020-10-29 20:33 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/entity/living/monster/EnderDragonEntity.java
> +     * @return Segment with the yaw and y
The line between these should be removed to keep with the javadoc style the rest of the repo uses.

2020-10-29 20:33 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/entity/living/monster/EnderDragonEntity.java
> +    private void updateBoundingBoxes(GeyserSession session) {
Can we get a javadoc comment on this?

2020-10-29 22:30 UTC, rtm516 approved these changes

2020-10-29 22:35 UTC, merged