Update CONTRIBUTING.md
GeyserMC/Geyser pull request #1787
Opened 2021-01-03 02:50 UTC by YHDiamond

there were a few code mistakes in this previous contributing.md which probably made a bad impression. so I fixed that and added a few more things

2021-01-03 06:18 UTC, theminecoder requested changes

2021-01-03 06:18 UTC, theminecoder commented on CONTRIBUTING.md
> +    @RandomAnnotation(AnnotationStuff)
This won't compile ;)

```suggestion
    @RandomAnnotation(stuff = true, moreStuff = "might exist")
```

2021-01-10 12:11 UTC, YHDiamond commented
Any news on this

2021-01-12 22:07 UTC, YHDiamond commented
Are there any compilation issues (besides using variable names that don't exist, etc) that I should fix?

2021-01-20 13:28 UTC, YHDiamond commented
Just to note: @lukeeey sent a form for contributors to fill out, and one of the questions asked about the CONTRIBUTING.md. This will hopefully make people's 'review' of the CONTRIBUTING.md 10/10

2021-01-20 13:44 UTC, lukeeey commented
@YHDiamond I actually discovered the other day that the contributing guidelines aren't just for how you format your code. They can also cover creating PRs as well as issues, but don't worry about that right now.

Here is some very good contribution guidelines: https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md

2021-01-20 13:45 UTC, YHDiamond commented
Ok, but the contributing guidelines should contain good code, right? If they don't contain good code it is embarrassing (imo).

2021-01-20 13:59 UTC, lukeeey commented
Yeah

2021-01-20 14:00 UTC, lukeeey approved these changes

2021-01-20 14:01 UTC, YHDiamond commented
thank you.  now we must wait for the merge power

2021-01-28 00:14 UTC, YHDiamond commented
Any news on this? Will it be merged? 
![image](https://user-images.githubusercontent.com/47502993/106071168-dbfba480-60d3-11eb-8bf2-e2ee397b44b5.png) lol though

2021-01-28 00:20 UTC, merged