Fix show-coordinates not disabling the coordinates display
GeyserMC/Geyser pull request #1864
Opened 2021-01-24 12:29 UTC by rtm516

This fixes the `show-coordinates` config option. It makes it so if `show-coordinates` is false then the client cannot choose to display coords and fixes the `reducedDebugInfo` to do the same but if it's true.

2021-01-25 03:54 UTC, Camotoy requested changes

2021-01-25 03:54 UTC, Camotoy commented on connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
> +        getWorldCache().setShowCoordinates(connector.getConfig().isShowCoordinates());
Nitpickiest thing: can you move this to the `connect` function? I think this function looks cleanest when it's dedicated to the StartGamePacket.

2021-01-25 03:54 UTC, Camotoy commented on connector/src/main/java/org/geysermc/connector/network/session/cache/WorldCache.java
> +        boolean check = !session.isReducedDebugInfo() && session.getConnector().getConfig().isShowCoordinates();
Check? Check what??

Legitimately it's almost 11 PM here and I had to think about this for a minute. I would recommend giving it a more apt name and/or adding a comment above.

2021-01-26 00:06 UTC, Camotoy approved these changes

2021-02-04 00:59 UTC, lukeeey approved these changes

2021-04-19 09:37 UTC, rtm516 commented
Superseded by #2151

2021-04-19 09:37 UTC, closed without merging