Add Dockerfile for standalone use
GeyserMC/Geyser pull request #1875
Opened 2021-01-27 23:27 UTC by JamesTheAwesomeDude

I don't know how widespread use this would get, but here it is if you want it.

If you wanted to give it a test run:

```bash
docker build -t geyser -f standalone.Dockerfile https://github.com/JamesTheAwesomeDude/Geyser.git
docker run -p 19132:19132/udp -v `pwd`/geyser:/var/lib/geyser geyser
```

2021-01-28 00:19 UTC, Camotoy commented
On behalf of RTM, the person who knows Docker best among us developers:

> Hmm, honestly it would probs be better just using the ones in the pterodactyl repo, could you link that and suggest he uses that instead? If he has a decent reason to add it then I'll look over it better tomorrow

Said repository: https://github.com/GeyserMC/pterodactyl-stuff/tree/docker-geyser

2021-01-28 00:19 UTC, rtm516 commented
I need to look at this better tomorrow but do these images not give you the same if not more functionality. They are designed for pterodactyl panel but should run on any system.
https://github.com/GeyserMC/pterodactyl-stuff/

2021-01-28 03:44 UTC, JamesTheAwesomeDude commented
> ~I need to look at this better tomorrow but do these images not give you the same if not more functionality. They are designed for pterodactyl panel but should run on any system.~

I had not seen those before — though those are just a wrapper around a shell script that fetches CI artefacts at runtime; that Dockerfile:

- does not store code in the r/o `image`, doing which is one of the points of Docker
- does not compile from source during the `docker build` stage

Conversely, this PR contains something more like a mainstream Dockerfile in the vein of the official ones on the Hub.

I'm not familiar with the Pterodactyl Panel internal architecture, so I can't comment on the interactions between it and Docker or whether this would actually be better for that use-case in the long run.

2021-02-03 19:22 UTC, rtm516 requested changes
Giving this a test it works fine, and we can set it up with quay.io so people can get the built docker image. I will add a note about this to the wiki after this is merged and quay.io is setup.

2021-02-03 19:22 UTC, rtm516 commented on standalone.Dockerfile
> +RUN git submodule update --init --recursive&&\
```suggestion
RUN git submodule update --init --recursive &&\
```

2021-03-31 15:32 UTC, rtm516 approved these changes

2023-06-15 00:34 UTC, matsyyy requested changes
While this PR is old, it would still be useful to the likes of me who want to use Geyser in docker.

2023-06-15 00:34 UTC, matsyyy commented on standalone.Dockerfile
> +	mvn clean install
Geyser uses Gradle now, so this would have to be gradle build instead

2023-06-15 00:34 UTC, matsyyy commented on standalone.Dockerfile
> +FROM adoptopenjdk/openjdk11:alpine-jre
geyser now uses java 16, soon, java 17? it warned me on my standalone console.

2023-06-15 00:34 UTC, matsyyy commented on standalone.Dockerfile
> +CMD ["java", "-jar", "/opt/Geyser/Geyser.jar"]
The file is now called Geyser-Standalone.jar

2023-06-15 00:34 UTC, matsyyy commented on standalone.Dockerfile
> +COPY --from=build ./bootstrap/standalone/target /opt/Geyser
i think this folder is outdated?

2024-07-03 23:21 UTC, onebeastchris commented
This PR is unfortunately stale/outdated - hence i'll close this. Thanks anyways!
While not a direct dockerfile, there are official ptero eggs available to use, which might serve a similar purpose: <https://github.com/GeyserMC/pterodactyl-stuff/>.

2024-07-03 23:21 UTC, closed without merging