Tiny stuff that should theoretically be better or has been bothering me
GeyserMC/Geyser pull request #2011
Opened 2021-03-07 20:43 UTC by Camotoy

2021-03-07 23:07 UTC, rtm516 requested changes

2021-03-07 23:07 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
>          attributesPacket.setAttributes(attributes);
Why not just inline this?

2021-03-07 23:07 UTC, rtm516 commented on connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaPlayEffectTranslator.java
>                  textPacket.setParameters(params);
Same as above

2021-03-07 23:18 UTC, Camotoy commented on connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
>          attributesPacket.setAttributes(attributes);
Good point.

2021-03-08 01:05 UTC, lukeeey commented on connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
> +        attributesPacket.setAttributes(Collections.singletonList(
one line like below?

2021-03-08 01:09 UTC, Camotoy commented on connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
> +        attributesPacket.setAttributes(Collections.singletonList(
Too long?

2021-03-31 15:15 UTC, Tim203 approved these changes

2021-03-31 18:15 UTC, merged