Connect Geyser players direct to the server for plugin versions
GeyserMC/Geyser pull request #2413
Opened 2021-07-24 03:55 UTC by Camotoy

This PR introduces the concept of using Netty's LocalChannel - a channel type that performs the same network actions, albeit locally in the Java runtime - in order to join the Java server without requiring a TCP connection. This introduces increased performance, always-correct IP addresses, and less configuration required (`remote` `address` and `remote` `port` are 99% irrelevant for plugin versions with this PR).

The code changes may cause plugin conflicts, but through testing any such problem has been solved.

2021-07-24 14:34 UTC, RednedEpic requested changes

2021-07-24 14:34 UTC, RednedEpic commented on bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeeInjector.java
> +                    "Please reach out to us on our Discord so we can hear feedback on your setup.");
```suggestion
            throw new UnsupportedOperationException("Geyser does not currently support multiple listeners with injection! " +
                    "Please reach out to us on our Discord at https://discord.gg/GeyserMC so we can hear feedback on your setup.");
```

2021-07-24 14:34 UTC, RednedEpic commented on bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/GeyserSpigotInjector.java
> +                if (m.getReturnType().getSimpleName().equals("ServerConnection")) {
```suggestion
                if (m.getReturnType().getSimpleName().equals("ServerConnection") || m.getReturnType().getSimpleName().equals("ServerConnectionListener")) {
```
Allows this to be used on a deobfuscated environment. Although this is not typically suggested at the moment, in the very near future Spigot/Paper are likely to move to full Mojang mappings so it's nice to be able to support that before that move is done.

2021-07-24 14:34 UTC, RednedEpic commented on connector/src/main/java/org/geysermc/connector/common/GeyserInjector.java
> +            bootstrap.getGeyserLogger().warning("Attempted to inject twice!");
```suggestion
            bootstrap.getGeyserLogger().warning("Geyser attempted to inject into the server connection handler twice! Please ensure you aren't using /reload or any plugin that (re)loads Geyser after the server has started.");
```

2021-07-31 16:49 UTC, Tim203 approved these changes

2021-07-31 16:52 UTC, RednedEpic approved these changes

2021-07-31 16:52 UTC, merged