Added config file support for extensions
GeyserMC/Geyser pull request #2785
Opened 2022-01-22 15:51 UTC by ImDaBigBoss

Language messages are here: [https://github.com/GeyserMC/languages/pull/94](https://github.com/GeyserMC/languages/pull/94)

2022-01-31 22:37 UTC, RednedEpic requested changes

2022-01-31 22:37 UTC, RednedEpic commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionLoader.java
> +    protected abstract ExtensionConfig config(@NonNull Extension extension, String name);
```suggestion
    protected abstract ExtensionConfig config(@NonNull Extension extension, @NonNull String name);
```

2022-01-31 22:37 UTC, RednedEpic commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +public interface ExtensionConfig {
Missing Nullable/NonNull annotations throughout.

2022-01-31 22:37 UTC, RednedEpic commented on core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionConfig.java
> +    private File file;
Should use Java NIO rather than Java IO .

2022-01-31 22:37 UTC, RednedEpic commented on core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionConfig.java
> +public class GeyserExtensionConfig implements ExtensionConfig {
```suggestion
public class YamlExtensionConfig implements ExtensionConfig {
```
I don’t want to lock configs to only YAML so it’s worth giving this a name pertinent to the format that is being used so other formats can be utilized in the future.

2022-01-31 22:37 UTC, RednedEpic commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionLoader.java
> +    @NonNull
Can’t this be null? What if an extension has no config?

2022-01-31 22:37 UTC, RednedEpic commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionLoader.java
> +    @NonNull
Same as above.

2022-02-02 06:20 UTC, Konicai requested changes
wordy stuff

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets if a config contains a value
```suggestion
     * Checks if a config contains a value
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets and integer from the config
```suggestion
     * Gets an integer from the config
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets if a value is an integer
```suggestion
     * Checks if a value is an integer
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets if a value is a long
```suggestion
     * Checks if a value is a long
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets if a value is a double
```suggestion
     * Checks if a value is a double
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets if a value is a string
```suggestion
     * Checks if a value is a string
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets if a value is a boolean
```suggestion
     * Checks if a value is a boolean
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets if a value is a list
```suggestion
     * Checks if a value is a list
```

2022-02-02 06:20 UTC, Konicai commented on api/geyser/src/main/java/org/geysermc/geyser/api/extension/ExtensionConfig.java
> +     * Gets a list form the config
```suggestion
     * Gets a list from the config
```

2022-02-07 21:45 UTC, iZeaoGamer commented
Who’s gay?

2022-03-18 00:08 UTC, rtm516 commented
I feel like this should also handle pulling the config out of the extension jar since it's not very clean to do and likely a lot of devs will want to do that.
https://github.com/rtm516/MCXboxBroadcast/blob/4a4cf5b24c79804ddbbc653898c632f005ad91ab/bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/MCXboxBroadcastExtension.java#L51-L68

2022-09-19 17:48 UTC, closed without merging