Events can be handled by any class
GeyserMC/Geyser pull request #3073
Opened 2022-06-19 17:44 UTC by ImDaBigBoss

The `Extension` class extends `EventListener`, and any class can implement it and then register it:
```java
GeyserApi.api().eventBus().register(new ClassThatImplementsEventListener());
```

Also:
* Loggers have the same implementation (`AbstractLogger`) so that we make sure they follow each other
* Stopped the `extensions` folder from being created at the server root for non standalone and moved it into the data folder.

2022-06-22 22:22 UTC, Camotoy reviewed
I'm not sure if we need a whole Logger interface - maybe we should just use Java's?

This PR looks fine to me otherwise. But, before we merge, we do need to figure out a good way for, say, Spigot plugins to reliably attach themselves to Geyser before Geyser initializes.

2022-06-22 22:22 UTC, Camotoy commented on api/geyser/src/main/java/org/geysermc/geyser/api/event/EventBus.java
> +
Extra space.

2022-06-23 06:31 UTC, ImDaBigBoss commented
I would suggest using the onLoad function for that, but I need to make sure that moving code around like that won’t break anything.

2022-07-02 06:59 UTC, ImDaBigBoss commented
> I'm not sure if we need a whole Logger interface - maybe we should just use Java's?
> 
> This PR looks fine to me otherwise. But, before we merge, we do need to figure out a good way for, say, Spigot plugins to reliably attach themselves to Geyser before Geyser initializes.

Java's one is full of things that we don't need in Geyser isn't it? I can remove the `AbstractLogger` and put it back to the way it was.

2022-07-02 19:32 UTC, ImDaBigBoss commented
I have no idea if this broke anything. This code needs checking by someone who knows Geyser better than me, but I was able to catch the init events by registering my listeners in the `onLoad` event of my spigot plugin.

2022-07-12 16:55 UTC, Camotoy commented
The only thing I'm wondering is if we should delay plugin loading *after* onEnable so plugins have a chance to register lifecycle events at any point during initialization.

2022-07-13 19:41 UTC, ImDaBigBoss commented
Do people really want Geyser to be slower? I thought you had been working on trying to make the load time faster.

2022-07-13 20:00 UTC, Camotoy commented
I think there's a difference here, since we're simply delaying triggering parts of the plugin. It doesn't really matter for us *when* the load time is. Our only requirement is that Geyser is booted by/around the time the server is ready.

2022-07-21 17:36 UTC, RednedEpic requested changes
Looks good for the most part. Just one nitpick from me.

2022-07-21 17:36 UTC, RednedEpic commented on api/geyser/src/main/java/org/geysermc/geyser/api/event/EventListener.java
> +public interface EventListener {
I'm not the biggest fan of calling this class `EventListener` for the reason that other API's (mainly Bukkit) typically use a `Listener` class as a place where the event handlers are actually held. In our case, this is just what exactly is registering the event, which could be a plugin or extension.

I think a name such as `EventRegistrar` could work. Not sure on the most ideal name but if you have any ideas feel free to suggest an alternative.

2022-08-19 17:20 UTC, ImDaBigBoss commented
Registering listeners is broken for now but the code for loading in onLoad is fixed.

2022-09-04 21:11 UTC, RednedEpic commented
Superseded by https://github.com/GeyserMC/Geyser/commit/f1da9d70728ad50cbff5c345052f8b18fabb06f2.

2022-09-04 21:11 UTC, closed without merging