Added tool break speeds & more
GeyserMC/Geyser pull request #3381
Opened 2022-11-03 08:36 UTC by ImDaBigBoss

- Added tool break speeds for custom items, so that we don't need to rely on tags that Mojang seems to have abandoned.
- Added `texture_type` to the armor component for custom items.
- Added an option to force display custom items as handheld. This means that items that bedrock can display an item like java would with `"parent": "item/handheld"` in the item model.

2022-11-03 08:38 UTC, ImDaBigBoss commented
I think there is something wrong with the break speeds on slabs. I've tested cobblestone slabs and they don't seem to be breaking correctly, even though they are in the break speeds list. Am I missing something?

2022-11-03 14:26 UTC, Camotoy requested changes

2022-11-03 14:26 UTC, Camotoy commented on api/geyser/src/main/java/org/geysermc/geyser/api/item/custom/NonVanillaCustomItemData.java
> -    boolean isTool();
While I'm not aware of anyone using this, we can't break API like this without proper deprecation.

2022-11-03 14:26 UTC, Camotoy commented on api/geyser/src/main/java/org/geysermc/geyser/api/item/custom/NonVanillaCustomItemData.java
> -        Builder tool(boolean isTool);
Same.

2022-11-11 19:08 UTC, Camotoy commented
Can you print an example output of the ItemComponentPacket with these changes?

2022-11-12 09:12 UTC, ImDaBigBoss commented
[ItemComponentPacket.zip](https://github.com/GeyserMC/Geyser/files/9994588/ItemComponentPacket.zip)
Sorry it's a zip, GitHub won't take json.

2022-12-13 04:38 UTC, Kas-tle commented
Note: do not attempt to run the build generated by this action as it will (likely) not work due to outdated mappings^

2022-12-13 04:40 UTC, Kas-tle commented
Also it seems that we unfortunately still cannot fix https://github.com/GeyserMC/Geyser/issues/3348 as it seems the `use_efficiency` sub-component of `digger` is non-functional

2023-03-06 17:45 UTC, Kas-tle commented
Given the changes that custom blocks required to get break speeds to function, I have implemented a fix for this in my custom blocks PR that basically implements server authoritative block breaking when a custom tool as used. See https://github.com/GeyserMC/Geyser/pull/3505. As such this would no longer be needed if that is merged. It also fixes the problem in more scenarios, as we can properly account for high level efficiency enchantments.

2023-03-06 17:47 UTC, closed without merging