fix sounds
GeyserMC/Geyser pull request #3956
Opened 2023-07-09 15:38 UTC by onebeastchris

This makes sure /playsound plays minecraft sounds; since we were not stripping the identifiers before looking up the sound.

The alternative solution would be to change the sound registry so removing the identifier is not needed

2023-07-20 23:49 UTC, Camotoy approved these changes

2023-07-21 00:03 UTC, Konicai requested changes
[this fallback](https://github.com/GeyserMC/Geyser/pull/3956/files#diff-0eae3bbc4f0770a824f16a5354bd07c417ce4ac4419f15005de95fe89a048c54R132-R136) is the only other place that `packetSound` is used, apart from the beginning of the method. With the commits to this file in the past couple months, `packetSound` no longer has any namespace trimmed. I would assume that the code I just linked is broken, considering that the method called expects no namespace.

2023-07-22 00:12 UTC, Konicai requested changes

2023-07-22 00:12 UTC, Konicai commented on core/src/main/java/org/geysermc/geyser/util/SoundUtils.java
> +        String soundIdentifier = removeMinecraftNamespace(packetSound);
I would merge these two lines

2023-07-22 01:10 UTC, Konicai approved these changes

2023-07-22 02:25 UTC, merged