Fixing FOV locks when changed world
GeyserMC/Geyser pull request #3978
Opened 2023-07-14 07:52 UTC by patyhank

Fix https://github.com/GeyserMC/Geyser/issues/3896

2023-07-14 14:37 UTC, onebeastchris requested changes

2023-07-14 14:37 UTC, onebeastchris commented on core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
> +        if (spectator) {
Why not use the spectator check a few lines above, aka https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/session/GeyserSession.java#L1763-L1772?
Additionally, is intended that spectator mode would have both the base and spectator ability layer?
See your own earlier issue/PR: https://github.com/GeyserMC/Geyser/issues/3769

2023-07-14 17:42 UTC, onebeastchris requested changes

2023-07-14 17:42 UTC, onebeastchris commented on core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
> +        abilityLayer.setLayerType(AbilityLayer.Type.SPECTATOR);
Now we would be setting the spectator layer for all gamemodes..
The check is still needed, but there was no need for two of them

2023-07-17 18:57 UTC, Konicai commented
Currently it looks like 
`abilityLayer.setLayerType(AbilityLayer.Type.SPECTATOR);` 
is simply overridden by the subsequent 
`abilityLayer.setLayerType(AbilityLayer.Type.BASE);`

And you're adding the exact same `abilityLayer` to the list in the packet twice.

This just looks like it reverts #3770 and honestly I'm skeptical if its an actual solution.

2023-07-19 07:23 UTC, patyhank commented
It looks like #3770 can be revert, it doesn't seem to be a problem in the latest version.
This PR doesn't seem to be necessary anymore.

2023-07-19 07:23 UTC, closed without merging