Feature: Structure block translation
GeyserMC/Geyser pull request #4521
Opened 2024-03-24 16:55 UTC by onebeastchris

Builds on https://github.com/GeyserMC/Geyser/pull/2044 - huge thanks to Camotoy for that.

Current issues/TO-DO's:
- [ ] fix offset application when we're changing rotations
- [ ] yeet debug

Opening as a draft in case someone wants to test this :p

2024-03-27 21:51 UTC, Tydium commented
I love you

2024-03-29 18:55 UTC, onebeastchris commented
I'm off to vacation so i can't continue this PR for a week. Currently, rotations combined with mirroring does work, but modifying the rotation/mirror or opening a structure block with a mirror/rotation applied on Bedrock causes havoc with the offsets - in other words, offset removing isn't quite working. Getting close though :p

2024-04-14 18:29 UTC, rtm516 requested changes

2024-04-14 18:29 UTC, rtm516 commented on core/src/main/java/org/geysermc/geyser/session/cache/StructureBlockCache.java
> +@Setter @Getter
Do we not normally keep these on separate lines?
```suggestion
@Setter
@Getter
```

2024-04-14 18:29 UTC, rtm516 commented on core/src/main/java/org/geysermc/geyser/translator/level/block/entity/StructureBlockBlockEntityTranslator.java
> +    @Override
```suggestion

    @Override
```

2024-04-14 18:29 UTC, rtm516 commented on core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockStructureBlockUpdateTranslator.java
> +        com.github.steveice10.mc.protocol.data.game.level.block.StructureRotation rotation = switch (settings.getRotation()) {
```suggestion
        StructureRotation rotation = switch (settings.getRotation()) {
```

2024-04-14 18:29 UTC, rtm516 commented on core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockStructureTemplateDataRequestTranslator.java
> +            com.github.steveice10.mc.protocol.data.game.level.block.StructureRotation rotation = switch (settings.getRotation()) {
```suggestion
            StructureRotation rotation = switch (settings.getRotation()) {
```

2024-04-14 18:29 UTC, rtm516 commented on core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockStructureTemplateDataRequestTranslator.java
> +public class BedrockStructureTemplateDataRequestTranslator extends PacketTranslator<StructureTemplateDataRequestPacket> {
This feels very similar to BedrockStructureBlockUpdateTranslator, could some of this be moved into a shared class to save code duplication?

2024-04-16 19:26 UTC, Kas-tle approved these changes

2024-04-17 21:20 UTC, rtm516 approved these changes

2024-04-17 21:21 UTC, merged