Update DeviceOs to latest protocol
GeyserMC/Geyser pull request #4553
Opened 2024-04-07 11:46 UTC by rtm516

Updated to follow the newly published protocol specification. Will probably need a floodgate update aswell.

https://github.com/CloudburstMC/protocol-docs/blob/master/enums/BuildPlatform.md

2024-04-07 11:47 UTC, onebeastchris approved these changes
Yeah, this will likely need a new Floodgate build

2024-04-07 12:51 UTC, Redned235 approved these changes

2024-04-07 18:00 UTC, Camotoy commented on common/src/main/java/org/geysermc/floodgate/util/DeviceOs.java
> +    HOLOLENS("Hololens"), // Removed from protocol but kept to keep numbers the same
Mark this as deprecated instead?

2024-04-07 18:00 UTC, Camotoy requested changes

2024-04-07 18:00 UTC, Camotoy commented on common/src/main/java/org/geysermc/floodgate/util/DeviceOs.java
> +    SONY("PlayStation"),
Just add a Javadoc indicating this isn't just for PS4. We can change the string though.

2024-04-07 20:12 UTC, Camotoy approved these changes

2024-04-07 21:25 UTC, Tim203 requested changes
I wouldn't mark them as deprecated instead I'd add it in a comment saying that those platforms are no longer in use.
Deprecated would indicate to me that they will be removed in the future, but I don't think they'd do that because it'd shift the enum values.

2024-04-07 23:33 UTC, rtm516 commented
> I wouldn't mark them as deprecated instead I'd add it in a comment saying that those platforms are no longer in use. Deprecated would indicate to me that they will be removed in the future, but I don't think they'd do that because it'd shift the enum values.

They removed Hololens from the docs but left the gap in the enum values so I think depricated is good, for this. They also marked the others as depricted. If they add more they could replace the old values.

2024-04-08 08:46 UTC, Tim203 approved these changes

2024-07-23 18:43 UTC, merged