Add Timeout to CompletableFuture in GeyserBungeePingPassthrough to Prevent Memory Leak
GeyserMC/Geyser pull request #4858
Opened 2024-07-14 08:27 UTC by ByteExceptionM

This PR addresses a memory leak issue in the `GeyserBungeePingPassthrough` class. The `getPingInformation` method has been updated to include a timeout in the `CompletableFuture`. This change prevents unprocessed packets from accumulating in the queue, which previously led to blocked Netty threads and unreleased `ByteBufs`, ultimately preventing players from joining. The problem appears to be a network issue, although it is more likely that the ProxyPingEvent is being blocked. This prevents Geyser from retrieving the MOTD and responding to appropriate requests. Bedrock needs the MOTD before a connection can be established. In addition, the network threads could be overloaded by this blocking, which leads to further connection issues.

### Changes Made:

**Added Timeout to `CompletableFuture`:**
   - Implemented a timeout to ensure that packets are processed within a reasonable timeframe.
   - This prevents the accumulation of unprocessed packets.

### Issue Verification:

#### Unprocessed Packets in Queue
In the first image, you can see a high number of unprocessed UDP packets in the queue on port 19132. This is an indication of faulty packet processing.

![image](https://github.com/user-attachments/assets/db261598-6604-4a00-a6e4-c54f45a10a0c)

#### Packet Dump Analysis
This image shows a packet dump, which indicates that packets were sent to the machine and network interface, forwarded to the Docker network interface, but were not processed by Geyser.

![image](https://github.com/user-attachments/assets/e82cca0d-8289-42b0-8bbc-50a399852d34)

### Memory Usage and Heap Dump Analysis:

#### Heap Dump Overview
The images provide an overview of the heap dump and memory usage of the proxy, highlighting the significant memory usage.

![image](https://github.com/user-attachments/assets/2bd5b0f3-f1b3-4570-8076-f26bfe1a2a76)
![image](https://github.com/user-attachments/assets/a74536e3-e0d0-4c42-83d5-96cc68e3d2a4)
![image](https://github.com/user-attachments/assets/7ca86035-800c-4def-a828-44c6aafeb568)

#### Problem Suspect 1
The next image and stack trace show Problem Suspect 1. The `epollEventLoopGroup-3-1` thread has a large memory footprint, retaining a substantial amount of memory.

![image](https://github.com/user-attachments/assets/a3075b11-cba9-4a78-a96e-7b0721cd0e20)

```
epollEventLoopGroup-3-1
  at jdk.internal.misc.Unsafe.park(ZJ)V ((Native Method))
  at java.util.concurrent.locks.LockSupport.park(Ljava/lang/Object;)V ()
  at java.util.concurrent.CompletableFuture$Signaller.block()Z ()
  at java.util.concurrent.ForkJoinPool.unmanagedBlock(Ljava/util/concurrent/ForkJoinPool$ManagedBlocker;)V ()
  at java.util.concurrent.ForkJoinPool.managedBlock(Ljava/util/concurrent/ForkJoinPool$ManagedBlocker;)V ()
  at java.util.concurrent.CompletableFuture.waitingGet(Z)Ljava/lang/Object; ()
  at java.util.concurrent.CompletableFuture.join()Ljava/lang/Object; ()
  at org.geysermc.geyser.platform.bungeecord.GeyserBungeePingPassthrough.getPingInformation(Ljava/net/InetSocketAddress;)Lorg/geysermc/geyser/ping/GeyserPingInfo; (GeyserBungeePingPassthrough.java:62)
  at org.geysermc.geyser.network.netty.GeyserServer.onQuery(Lio/netty/channel/Channel;Ljava/net/InetSocketAddress;)Lorg/cloudburstmc/protocol/bedrock/BedrockPong; (GeyserServer.java:310)
  at org.geysermc.geyser.network.netty.handler.RakPingHandler.channelRead0(Lio/netty/channel/ChannelHandlerContext;Lorg/cloudburstmc/netty/channel/raknet/RakPing;)V (RakPingHandler.java:48)
  at org.geysermc.geyser.network.netty.handler.RakPingHandler.channelRead0(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (RakPingHandler.java:37)
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (SimpleChannelInboundHandler.java:99)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Ljava/lang/Object;)Lio/netty/channel/ChannelHandlerContext; (AbstractChannelHandlerContext.java:412)
  at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.onUnconnectedPing(Lio/netty/channel/ChannelHandlerContext;Lio/netty/channel/socket/DatagramPacket;Lio/netty/buffer/ByteBuf;J)V (RakServerOfflineHandler.java:134)
  at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(Lio/netty/channel/ChannelHandlerContext;Lio/netty/channel/socket/DatagramPacket;)V (RakServerOfflineHandler.java:116)
  at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (RakServerOfflineHandler.java:46)
  at org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (AdvancedChannelInboundHandler.java:45)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Ljava/lang/Object;)Lio/netty/channel/ChannelHandlerContext; (AbstractChannelHandlerContext.java:412)
  at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerRateLimiter.channelRead0(Lio/netty/channel/ChannelHandlerContext;Lio/netty/channel/socket/DatagramPacket;)V (RakServerRateLimiter.java:148)
  at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerRateLimiter.channelRead0(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (RakServerRateLimiter.java:35)
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (SimpleChannelInboundHandler.java:99)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Ljava/lang/Object;)Lio/netty/channel/ChannelHandlerContext; (AbstractChannelHandlerContext.java:412)
  at org.geysermc.geyser.network.netty.handler.RakConnectionRequestHandler.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (RakConnectionRequestHandler.java:80)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Ljava/lang/Object;)Lio/netty/channel/ChannelHandlerContext; (AbstractChannelHandlerContext.java:412)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (DefaultChannelPipeline.java:1407)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:440)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;)V (AbstractChannelHandlerContext.java:420)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(Ljava/lang/Object;)Lio/netty/channel/ChannelPipeline; (DefaultChannelPipeline.java:918)
  at org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(L [...]

2024-07-14 15:58 UTC, onebeastchris requested changes

2024-07-14 15:58 UTC, onebeastchris commented on bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePingPassthrough.java
> +            proxyServer.getLogger().log(Level.SEVERE, "Failed to get ping information for " + inetSocketAddress, cause);
Please use the Geyser logger here - you can access it via `GeyserImpl.getInstance().getLogger()`.

2024-07-14 18:57 UTC, Konicai commented on bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePingPassthrough.java
> +
would probably be wise to do something similar to this: https://github.com/GeyserMC/Geyser/blob/9cdda70/core/src/main/java/org/geysermc/geyser/session/GeyserSession.java#L1092

2024-07-14 18:57 UTC, Konicai commented on core/src/main/java/org/geysermc/geyser/ping/IGeyserPingPassthrough.java
> +     * Get the ping information, including the MOTD and player count, from the server
```suggestion
     * Gets the ping information, including the MOTD and player count, from the server
```

2024-07-15 21:29 UTC, Tjorven-Liebe approved these changes
This seems like a legitimate way to fix the memory leak. Approved.

2024-07-15 21:33 UTC, JonasDevDE approved these changes
nice fix.

2024-07-15 22:20 UTC, onebeastchris approved these changes
two small nitpicks, lgtm otherwise

2024-07-15 22:20 UTC, onebeastchris commented on bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePingPassthrough.java
> +
```suggestion
```

2024-07-15 22:20 UTC, onebeastchris commented on bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePingPassthrough.java
> +
```suggestion
```

2024-07-16 09:23 UTC, merged