Unify repository definition
GeyserMC/Geyser pull request #4953
Opened 2024-08-08 22:29 UTC by onebeastchris

These changes ensure that there is a single point where we define maven repos - instead of multiple. Done similarly in the floodgate-neoforge PR; works like a charm there. 
Unfortunately, the build-logic's build.gradle.kts will have it's own repo section, but to my knowledge that is unavoidable (and not a huge issue, as that specifically affects the plugins used in there)

2024-08-08 22:32 UTC, rtm516 requested changes

2024-08-08 22:32 UTC, rtm516 commented on build-logic/src/main/kotlin/geyser.build-logic.gradle.kts
> +    maven("https://repo.opencollab.dev/main")
Is this meant to be here 2x?

2024-08-08 22:32 UTC, onebeastchris commented on build-logic/src/main/kotlin/geyser.build-logic.gradle.kts
> +    maven("https://repo.opencollab.dev/main")
oops, nope

2024-08-09 00:13 UTC, Konicai approved these changes

2024-08-09 00:13 UTC, Konicai commented on build-logic/src/main/kotlin/geyser.build-logic.gradle.kts
> +    // ViaVersion
```suggestion
    }

    // ViaVersion
```

2024-08-09 05:37 UTC, Camotoy approved these changes

2024-08-09 09:08 UTC, rtm516 approved these changes

2024-08-09 09:35 UTC, merged