Add support for extended world height
GeyserMC/Geyser pull request #5002
Opened 2024-08-27 20:35 UTC by RaphiMC

Adds support for data driven world heights for the overworld dimension. Has a min Y limit of -512 and a max Y limit of 512.

Showcase with a 512 block high world:
![image](https://github.com/user-attachments/assets/febf846b-a5f7-435b-b366-bb3705f86418)

2024-08-27 22:16 UTC, onebeastchris commented on core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
> +        }
let's add some debug logging here that the world height was extended, just in case this could cause any issues at a later point

2024-08-28 09:29 UTC, onebeastchris approved these changes

2024-08-28 19:52 UTC, Konicai requested changes

2024-08-28 19:52 UTC, Konicai commented on core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
> +        }
Does this assume `dimensionType` is always overworld? For example, has <https://github.com/GeyserMC/Geyser/blob/3d7e62a408b2b4a6f86430e940a0219c5b595fa0/core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java#L88-L97> been taken into account?

Does the `min` and `max` need to be constrained to a multiple of 16 as per Camo's [reference](https://learn.microsoft.com/en-us/minecraft/creator/documents/datadrivenoverworldheight?view=minecraft-bedrock-stable)?

Some other minor notes:
- although it isn't noted, this project typically doesn't use `final` for all local variables
- add a note for the magic 5 for the generator type - is it the Void enum constant you sent a screenshot of?

2024-08-28 19:52 UTC, Konicai commented on core/src/main/java/org/geysermc/geyser/level/BedrockDimension.java
> +    public static final BedrockDimension THE_END = new BedrockDimension(0, 256, true, END_ID);
Storing the `bedrockId` here publicly but then always having to call `int javaToBedrock(BedrockDimension dimension)` (method is named poorly right now lol) doesn't seem ideal.

There are probably a lot of ways of fixing this. Maybe consider turning this into a class and moving the customization of the bedrock nether ID here

2024-09-24 21:37 UTC, Konicai approved these changes

2024-09-24 21:37 UTC, Konicai commented on core/src/main/java/org/geysermc/geyser/level/BedrockDimension.java
> +public class BedrockDimension {
Are we using equals or hashcode anywhere currently? Remove if possible

2024-09-24 21:37 UTC, Konicai commented on core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
> +    private BedrockDimension bedrockOverworldDimension = BedrockDimension.OVERWORLD;
getter annotation is already on the class level, should be able to remove it

2024-09-28 20:08 UTC, Camotoy commented on core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java
> +import org.geysermc.geyser.erosion.GeyserboundHandshakePacketHandler;
Not sure where this import came from.

2024-09-30 17:38 UTC, Camotoy commented on core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
> +                minY = Math.min(minY, this.dimensionType.minY());
This line and the next needs to be `javaDimension.min/maxY()`

2024-10-03 16:12 UTC, merged